export const LOAD_PEOPLE_SUCCESS = 'LOAD_PEOPLE_SUCCESS'; 
export const UPDATE_PERSON_SUCCESS = 'UPDATE_PERSON_SUCCESS'; 
export const CREATE_PERSON_SUCCESS = 'CREATE_PERSON_SUCCESS'; 
export const DELETE_PERSON_SUCCESS = 'DELETE_PERSON_SUCCESS'; 
